apiVersion: v1
kind: Service
metadata:
  labels:
    app: bcs
  name: bcs
  namespace: blockchain
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: bcs
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: bcs
  name: bcs
  namespace: blockchain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bcs
  template:
    metadata:
      labels:
        app: bcs
    spec:
      containers:
      - env:
        - name: VM_HOSTNAME
          value: k8s-master
        image: 192.168.56.105:5000/oracle/obcs-provision
        imagePullPolicy: IfNotPresent
        name: bcs
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /var/run
          name: bcs-persistent-storage
        - mountPath: ~/obcs_workspace
          name: bcs-workspace-persistent-storage
      volumes:
      - hostPath:
          path: /var/run
          type: Directory
        name: bcs-persistent-storage
      - hostPath:
          path: /u01/data/obcs_workspace
          type: Directory
        name: bcs-workspace-persistent-storage
